services:
  - type: web
    name: student-attendance-system
    env: python
    plan: free
    buildCommand: export CMAKE_BUILD_PARALLEL_LEVEL=1 MAKEFLAGS="-j1" && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -w 1 --threads 2 app:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: 5000
